# .github/workflows/scheduler.yml

name: Run Python Script and Alert via Telegram

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (you can adjust this)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install BeautifulSoup
          pip install json
          pip install os
          

      - name: Run Python script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python app.py
