# .github/workflows/scheduler.yml

name: Run Python Script and Alert via Telegram

on:
  schedule:
    - cron: '0/5 * * * *' # Adjust this as needed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          pip install requests
          pip install bs4

      - name: Run Python script
        run: |
          python app.py
